// Code generated by goctl. DO NOT EDIT.
package types

type PingResponse struct {
	Message string `json:"message"`
}

type HelloRequest struct {
	Name string `json:"name"`
}

type HelloResponse struct {
	Message string `json:"message"`
}