// Code generated by goctl. DO NOT EDIT.
package types

type PingResponse struct {
	Message string `json:"message"`
}

type HelloRequest struct {
	Name string `json:"name"`
}

type HelloResponse struct {
	Message string `json:"message"`
}
// RetryResponse 重试测试响应
type RetryResponse struct {
	Message string `json:"message"`
}

type HiResponse struct {
	Message string `json:"message"`
}
