// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/admin-core/ping",
				Handler: PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin-core/hello",
				Handler: HelloHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin-core/test_retry",
				Handler: TestRetryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin-core/hi/:name",
				Handler: HiHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin-core/hi/f/ff",
				Handler: Hi2Handler(serverCtx),
			},
		},
	)
}