// Code generated by goctl. DO NOT EDIT.
// Source: admincore.proto

package rpcclient

import (
	"context"

	"rpc/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request       = rpc.Request
	Response      = rpc.Response
	HelloRequest  = rpc.HelloRequest
	HelloResponse = rpc.HelloResponse

	Rpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
		Testerr(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRpc struct {
		cli zrpc.Client
	}
)

func NewRpc(cli zrpc.Client) Rpc {
	return &defaultRpc{
		cli: cli,
	}
}

func (m *defaultRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultRpc) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Hello(ctx, in, opts...)
}

func (m *defaultRpc) Testerr(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Testerr(ctx, in, opts...)
}